kind = "web"
previewPath = "/"
title = "Etoolspot"
version = "1.0.0"
id = "artifacts/etoolspot"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19228

[services.development]
run = "pnpm --filter @workspace/etoolspot run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/etoolspot", "run", "build" ]
publicDir = "artifacts/etoolspot/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19228"
BASE_PATH = "/"
